name: gdp2medals
dependencies:
- cairo=1.12.18
- certifi
- cycler=0.10.0
- decorator=4.0.10
- entrypoints=0.2.2
- fontconfig=2.11.1
- harfbuzz=0.9.39
- ipykernel=4.3.1
- ipython=5.0.0
- ipython_genutils=0.1.0
- ipywidgets
- jinja2=2.8
- jsonschema=2.5.1
- jupyter=1.0.0
- jupyter_client=4.3.0
- jupyter_console=5.0.0
- jupyter_core=4.1.0
- libffi=3.2.1
- libgfortran=3.0.0
- libsodium=1.0.10
- markupsafe=0.23
- matplotlib
- nbconvert=4.2.0
- nbformat=4.0.1
- ncurses=5.9
- notebook=4.2.2
- numpy=1.11.1
- openssl=1.0.2h
- pandas=0.18.1
- pcre=8.39
- pickleshare=0.7.3
- pip=8.1.2
- pixman=0.32.6
- ptyprocess=0.5.1
- pygments=2.1.3
- pyparsing=2.1.4
- pyqt=4.11.4
- python=3.5.2
- python-dateutil=2.5.3
- pytz=2016.6.1
- pyzmq=15.3.0
- qt=4.8.7
- qtconsole=4.2.1
- readline=6.2
- requests=2.10.0
- scikit-learn=0.17.1
- scipy=0.18.0
- seaborn=0.7.0
- setuptools=25.1.6
- simplegeneric=0.8.1
- sip=4.18
- six=1.10.0
- sqlite=3.13.0
- terminado=0.6
- tornado=4.4.1
- traitlets=4.2.2
- wcwidth=0.1.7
- wheel=0.29.0
- xz=5.2.2
- zeromq
- zlib=1.2.8
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==4.3.0
  - jupyter-console==5.0.0
  - jupyter-core==4.1.0
  - wbdata==0.2.7

